# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Newton
tagline:             'A Hacker like jekyll theme'
description:         'oonlab is crafted with <3 by ariestiyansyah.'
url:                 http://mbazima.me
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Newton Mbazima
  url:               https://mbazima.me
  email:             nmbazima@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/nmbazima
twitter:			
disqus:             testnmbazima

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu

# Custom variables
owner : "NMbazima"
year : "2020"
